### ISSUE TITLE
bibtexconv 1.3.0 build issue

### ISSUE THREAD

**Issue by chenrui333** [dreibh/bibtexconv#2]
```
grammar.yy:123.7-12: invalid directive: `%empty'
```

relates to https://github.com/Homebrew/homebrew-core/pull/84939

**Comment by dreibh** [comment]
The source of the build issue seems to be this: https://www.gnu.org/software/bison/manual/html_node/Empty-Rules.html .

Which version of bison are you using for the build?

**Comment by chenrui333** [comment]
I think, it could be my bison version issue then (it happened recently with my another PR), thanks for the direction.

**Comment by chenrui333** [comment]
yeah, updating to use latest bison works for me, closing the issue now. Thanks @dreibh!
